songkg7/o2

src/jekyll.ts, src/main.ts
property 를 통해 plugin 을 전달하여 setting 참조를 유지합니다.
=> feat: o2-4 Global scope settings

src/jekyll.ts, src/main.ts, src/settings.ts
- fs 와 path library 를 사용하여 게시할 문서를 이동시킵니다
=> feat: move files to target folder by published by jekyll

README.md, package-lock.json, src/jekyll.ts
- 마크다운 파일 검색 최적화
- 가독성 개선
resolve #8
=> duplicate code clean up and some documentation

src/jekyll.ts
This pull request applies style fixes from code review by [CodeFactor](https://www.codefactor.io).
---
For more information, click [here](https://www.codefactor.io/repository/github/songkg7/o2/commit/73ab0bf3e7b1486a54aa6dd253d0e083f2737dd7).
=> Apply fixes from CodeFactor

src/jekyll/chirpy.ts, src/main.ts, src/settings.ts, src/tests/chirpy.test.ts
=> refactor: clean code

src/jekyll/chirpy.ts, src/settings.ts
console.log 는 debug 창으로만 확인이 되기 때문에 에러가 발생해도 유저가 알기 힘든 문제가 있다.
console.log 대신 유저에게 명확한 내용 전달을 위해 notice 를 사용한다
=> refactor: use notice instead of console

README.md, src/jekyll/chirpy.ts, src/main.ts, src/settings.ts
Issue Number: resolve #17
**change default directory name**
- resources -> attachments
- customize the attachments path
=> feat: custom attachments directory setting

.github/workflows/node.js.yml
add code coverage report in PR
=> chore: add codecov action

.circleci/config.yml, .github/workflows/ci.yml, .github/workflows/node.js.yml, .gitignore, README.md, jest.config.js
=> chore: update github action

src/ObsidianCallout.ts, src/ObsidianRegex.ts, src/jekyll/chirpy.ts, src/tests/chirpy.test.ts
Issue Number: resolve #24 
From now on, plugin can convert all obsidian callout keywords.
=> feat: #24 support callout syntax perfectly

src/settings.ts
none validation for Jekyll
Issue Number: resolve #43 
Jekyll path validation
=> fix: add target path validation and notice

package-lock.json, src/ObsidianRegex.ts, src/jekyll/CommentsConverter.ts, src/jekyll/chirpy.ts, src/tests/CommentsConverter.test.ts
Issue Number: resolve #67 
**AS-IS**
`%%This is a comment%%`
**TO-BE**
``
=> feat: o2-67 support comments syntax

README.md, src/ObsidianRegex.ts, src/core/Converter.ts, src/core/ConverterChain.ts, src/jekyll/CalloutConverter.ts, src/jekyll/CommentsConverter.ts, src/jekyll/EmbedsConverter.ts, src/jekyll/FootnotesConverter.ts, src/jekyll/FrontMatterConverter.ts, src/jekyll/ResourceLinkConverter.ts, src/jekyll/WikiLinkConverter.ts, src/jekyll/chirpy.ts, src/main.ts, src/settings.ts, src/tests/CalloutConverter.test.ts, src/tests/CommentsConverter.test.ts, src/tests/ConverterChain.test.ts, src/tests/EmbedsConverter.test.ts, src/tests/FootnotesConverter.test.ts, src/tests/FrontMatterConverter.test.ts, src/tests/ObsidianRegex.test.ts, src/tests/ResourceLinkConverter.test.ts, src/tests/WikiLinkConverter.test.ts, src/utils.ts
From now on, users can resize image height. follow:
**AS-IS**
```text
```
**TO-BE**
```text
```
- apply indent 2
=> feat: resize image height

.github/pull_request_template.md, package-lock.json, src/ObsidianRegex.ts, src/jekyll/ResourceLinkConverter.ts, src/tests/ResourceLinkConverter.test.ts
Issue Number: fix #82 
- remove unnecessary checkbox within pr template
=> fix: #82 should not remove empty line

src/jekyll/FilenameConverter.ts, src/jekyll/chirpy.ts, src/tests/FilenameConverter.test.ts
=> fix: #81 remove special symbol or char contained within title

README.md, src/ObsidianRegex.ts, src/jekyll/CurlyBraceConverter.ts, src/jekyll/chirpy.ts, src/settings.ts, src/tests/CurlyBraceConverter.test.ts
Issue Number: resolve #97 
(Optional) From now on, `{{ context }}` is converted to `{% raw %}{{ context }}{% endraw %}`.
=> feat: #97 Escaping double curly braces inside Markdown code block

.github/workflows/auto-merge.yml
=> ci: add auto-merge action

.github/dependabot.yml, .github/workflows/auto-merge.yml
=> ci: Update github action

src/ObsidianRegex.ts, src/jekyll/chirpy.ts, src/tests/WikiLinkConverter.test.ts
Issue Number: resolve #113 
Removed some notifications because I felt like there were too many of them
=> fix: remove square brackets in long contexts correctly (#118

README.md, package-lock.json, src/jekyll/FrontMatterConverter.ts, src/jekyll/chirpy.ts, src/settings.ts, src/tests/FrontMatterConverter.test.ts
Issue Number: resolve #112 
You can replace `updated` frontmatter with `date` frontmatter.
=> feat: #112 use updated frontmatter as the title of the post

src/jekyll/FrontMatterConverter.ts, src/tests/FrontMatterConverter.test.ts
You can convert normally even when there are no updated fields.
=> fix: undefined updated property
